apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluent-bit-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluent-bit-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: kube-system
roleRef:
  kind: Role
  name: fluent-bit-role
  apiGroup: rbac.authorization.k8s.io
